import os
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

import app as platform_app
from app import create_app
from namengine.core.schemas import NameResult, ValidationResult, ValidationStatus
from namengine.core.storage import get_session_snapshot, save_session
from namengine.core.briefs import build_brief
from namengine.verticals import get_vertical


def _ai_names():
    return [
        NameResult(
            id=f"baby-{index}",
            name=name,
            slug=name.lower(),
            pronunciation=name,
            tagline="AI-created candidate.",
            meaning="Generated by the AI naming engine.",
            why_this_name="Chosen by the LLM-first taste engine.",
            fit_note="Matches the supplied brief.",
            risks=["Review cultural and family fit."],
            tags=["ai"],
            scores={"callability": 0.9, "warmth": 0.85, "distinctiveness": 0.8},
            validation=[
                ValidationResult(
                    module="baby_gender_direction",
                    status=ValidationStatus.PASS,
                    label="Gender direction",
                    message="Fits the requested direction.",
                )
            ],
            metadata={"source": "openai", "provider": "openai"},
        )
        for index, name in enumerate(
            ["Sakura", "Hana", "Yumi", "Emi", "Aiko", "Mei", "Rina", "Kiko"],
            start=1,
        )
    ]


class PhaseThirtyTwoBabyAiPrimaryGenerationTest(unittest.TestCase):
    def setUp(self):
        self.tempdir = tempfile.TemporaryDirectory()
        self.previous_db = os.environ.get("NAMENGINE_DB_PATH")
        self.previous_ai_verticals = os.environ.get("NAMENGINE_AI_PRIMARY_VERTICALS")
        os.environ["NAMENGINE_DB_PATH"] = str(Path(self.tempdir.name) / "namengine.sqlite3")
        os.environ["NAMENGINE_AI_PRIMARY_VERTICALS"] = "baby"
        self.client = create_app().test_client()

    def tearDown(self):
        self.tempdir.cleanup()
        if self.previous_db is None:
            os.environ.pop("NAMENGINE_DB_PATH", None)
        else:
            os.environ["NAMENGINE_DB_PATH"] = self.previous_db
        if self.previous_ai_verticals is None:
            os.environ.pop("NAMENGINE_AI_PRIMARY_VERTICALS", None)
        else:
            os.environ["NAMENGINE_AI_PRIMARY_VERTICALS"] = self.previous_ai_verticals

    def test_baby_results_route_requests_ai_when_openai_is_configured(self):
        with patch.object(platform_app, "is_ai_generation_configured", return_value=True), patch.object(
            platform_app, "generate_names", return_value=_ai_names()
        ) as mocked_generate:
            response = self.client.get("/baby/results?gender=Girl&style=Playful&cultural_heritage=Japanese")

        self.assertEqual(response.status_code, 200)
        self.assertTrue(mocked_generate.call_args.kwargs["use_ai"])

    def test_cached_fallback_baby_session_is_stale_when_ai_primary_is_available(self):
        vertical = get_vertical("baby")
        brief = build_brief(vertical, {"gender": "Girl", "style": "Playful"})
        fallback_name = NameResult(
            id="baby-1",
            name="Clara",
            slug="clara",
            validation=[
                ValidationResult(
                    module="baby_gender_direction",
                    status=ValidationStatus.PASS,
                    label="Gender direction",
                    message="Fits the requested direction.",
                )
            ],
            metadata={"source": "baby_fallback", "provider": "fallback"},
        )
        with patch.object(platform_app, "is_ai_generation_configured", return_value=True):
            self.assertFalse(platform_app._cached_names_match_current_rules(vertical, brief, [fallback_name]))

    def test_cached_ai_baby_session_remains_valid_when_ai_primary_is_available(self):
        vertical = get_vertical("baby")
        brief = build_brief(vertical, {"gender": "Girl", "style": "Playful"})
        with patch.object(platform_app, "is_ai_generation_configured", return_value=True):
            self.assertTrue(platform_app._cached_names_match_current_rules(vertical, brief, _ai_names()))


if __name__ == "__main__":
    unittest.main()
