import os
import tempfile
import unittest
from pathlib import Path
from unittest.mock import patch

import app as platform_app
from app import create_app
from namengine.core.schemas import NameResult
from namengine.verticals import get_vertical


class PhaseThirtyFiveAiCostSafetyDefaultsTest(unittest.TestCase):
    def setUp(self):
        self.tempdir = tempfile.TemporaryDirectory()
        self.previous_db = os.environ.get("NAMENGINE_DB_PATH")
        self.previous_ai_verticals = os.environ.get("NAMENGINE_AI_PRIMARY_VERTICALS")
        os.environ["NAMENGINE_DB_PATH"] = str(Path(self.tempdir.name) / "namengine.sqlite3")
        os.environ.pop("NAMENGINE_AI_PRIMARY_VERTICALS", None)
        self.client = create_app().test_client()

    def tearDown(self):
        self.tempdir.cleanup()
        if self.previous_db is None:
            os.environ.pop("NAMENGINE_DB_PATH", None)
        else:
            os.environ["NAMENGINE_DB_PATH"] = self.previous_db
        if self.previous_ai_verticals is None:
            os.environ.pop("NAMENGINE_AI_PRIMARY_VERTICALS", None)
        else:
            os.environ["NAMENGINE_AI_PRIMARY_VERTICALS"] = self.previous_ai_verticals

    def test_baby_pet_and_business_default_to_ai_primary_when_openai_is_configured(self):
        baby = get_vertical("baby")
        pet = get_vertical("pet")
        business = get_vertical("business")
        with patch.object(platform_app, "is_ai_generation_configured", return_value=True):
            self.assertTrue(platform_app._should_use_ai_for_vertical(baby))
            self.assertTrue(platform_app._should_use_ai_for_vertical(pet))
            self.assertTrue(platform_app._should_use_ai_for_vertical(business))

    def test_ai_primary_env_override_can_narrow_vertical_opt_in(self):
        baby = get_vertical("baby")
        pet = get_vertical("pet")
        business = get_vertical("business")
        os.environ["NAMENGINE_AI_PRIMARY_VERTICALS"] = "baby"
        with patch.object(platform_app, "is_ai_generation_configured", return_value=True):
            self.assertTrue(platform_app._should_use_ai_for_vertical(baby))
            self.assertFalse(platform_app._should_use_ai_for_vertical(pet))
            self.assertFalse(platform_app._should_use_ai_for_vertical(business))

    def test_business_results_route_uses_openai_prompt_pipeline_when_configured(self):
        ai_names = [
            NameResult(
                id="business-1",
                name="Northmark",
                slug="northmark",
                tagline="A confident name for operators.",
                why_this_name="Generated by the OpenAI naming prompt pipeline.",
                fit_note="Fits a credible B2B operations brief.",
                scores={"clarity": 0.9, "distinctiveness": 0.85, "market_fit": 0.88},
                metadata={"source": "openai", "provider": "openai"},
            )
        ]
        route = "/business/results?business_description=Operations+support&audience=B2B+buyers&style=Clear+and+credible"
        with patch.object(platform_app, "is_ai_generation_configured", return_value=True), patch.object(
            platform_app, "generate_with_router", return_value=ai_names
        ) as generate:
            response = self.client.get(route)

        self.assertEqual(response.status_code, 200)
        self.assertEqual(generate.call_args.kwargs["providers"], [platform_app.ModelProvider.OPENAI])
        self.assertFalse(generate.call_args.kwargs["fallback_on_provider_error"])
        self.assertIn("Northmark", response.get_data(as_text=True))


if __name__ == "__main__":
    unittest.main()
