"""Core platform contracts and shared engine modules."""

from .ai_generation import (
    AIGenerationError,
    build_generation_prompt,
    generate_ai_names,
    is_ai_generation_configured,
    parse_ai_generation_response,
)
from .briefs import build_brief
from .compare import build_compare_items
from .generation import generate_names
from .model_router import (
    generate_with_router,
    route_generation,
    score_name_result,
    score_provider_results,
    select_best_candidates,
)
from .quality import (
    QualityBrief,
    QualityRunResult,
    load_quality_briefs,
    run_quality_brief,
    summarize_quality_runs,
)
from .progress import PROGRESS_STEPS, build_trust_cue
from .pet_portrait import (
    build_pet_portrait_prompt,
    ensure_pet_portrait_for_chosen,
    is_pet_portrait_generation_configured,
    pet_portrait_runtime_config,
    pet_portrait_url_from_metadata,
    portrait_details_from_brief,
)
from .provider_performance import (
    ProviderPerformance,
    build_provider_performance,
)
from .reactions import ReactionError, build_reaction
from .refinement import build_reaction_effect_summary, refine_session
from .schemas import (
    ChosenName,
    GenerationCandidate,
    ModelProvider,
    NamingBrief,
    NamingSession,
    NameResult,
    ProviderResult,
    Question,
    Reaction,
    ReactionValue,
    RefinementRequest,
    TasteProfile,
    ValidationResult,
    ValidationStatus,
    VerticalConfig,
)
from .storage import (
    get_database_path,
    get_chosen_snapshot,
    get_reaction_counts,
    get_session_snapshot,
    get_session_chain_snapshots,
    get_taste_profile,
    get_validation_results,
    get_provider_performance,
    initialize_database,
    refresh_provider_performance,
    save_chosen_name,
    save_reaction,
    save_session,
    save_taste_profile,
    save_validation_results,
    StorageError,
    update_chosen_metadata,
)
from .taste import build_taste_profile
from .validation import validate_result, validate_results
from .vertical_ui import (
    REQUIRED_ASSET_KEYS,
    REQUIRED_THEME_KEYS,
    validate_vertical_ui_contract,
    vertical_theme_style,
)

__all__ = [
    "build_brief",
    "build_generation_prompt",
    "build_pet_portrait_prompt",
    "build_provider_performance",
    "build_trust_cue",
    "build_compare_items",
    "build_reaction",
    "build_reaction_effect_summary",
    "build_taste_profile",
    "ChosenName",
    "AIGenerationError",
    "generate_ai_names",
    "generate_names",
    "generate_with_router",
    "GenerationCandidate",
    "get_chosen_snapshot",
    "get_database_path",
    "get_reaction_counts",
    "get_session_snapshot",
    "get_session_chain_snapshots",
    "get_taste_profile",
    "get_validation_results",
    "get_provider_performance",
    "ensure_pet_portrait_for_chosen",
    "initialize_database",
    "is_ai_generation_configured",
    "is_pet_portrait_generation_configured",
    "load_quality_briefs",
    "ModelProvider",
    "NamingBrief",
    "NamingSession",
    "NameResult",
    "ProviderResult",
    "ProviderPerformance",
    "PROGRESS_STEPS",
    "Question",
    "QualityBrief",
    "QualityRunResult",
    "parse_ai_generation_response",
    "pet_portrait_url_from_metadata",
    "pet_portrait_runtime_config",
    "portrait_details_from_brief",
    "Reaction",
    "ReactionError",
    "refine_session",
    "refresh_provider_performance",
    "route_generation",
    "run_quality_brief",
    "save_chosen_name",
    "save_reaction",
    "save_session",
    "save_taste_profile",
    "save_validation_results",
    "score_name_result",
    "score_provider_results",
    "select_best_candidates",
    "StorageError",
    "summarize_quality_runs",
    "ReactionValue",
    "REQUIRED_ASSET_KEYS",
    "REQUIRED_THEME_KEYS",
    "RefinementRequest",
    "TasteProfile",
    "ValidationResult",
    "ValidationStatus",
    "VerticalConfig",
    "validate_vertical_ui_contract",
    "update_chosen_metadata",
    "validate_result",
    "validate_results",
    "vertical_theme_style",
]
